build:
  image: bjodah/bjodahimg:v1.1
  commands:
    - cd ./input
    - ./build.sh
    - cd -
    - mkdir deploy
    - echo "This folder is emptied by CI script" >deploy/WARNING.txt
    - cp output/main.pdf output/supp_mater.pdf deploy/

deploy:

  rsync:
    host: hera.physchem.kth.se
    port: 22
    user: stopped_flow
    source: deploy/
    target: ~/public_html
    recursive: true
    delete: true
