image: bjodah/dockerfile-bjodah-scicomp
git:
    path: github.com/bjodah/chemreac-stiffness
script:
  - cd ./input
  - ./build.sh
  - cd ../output
  - scp main.pdf supp_mater.pdf stopped-flow@hera.physchem.kth.se:~/
